name: sereneeosman_doc
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - ipython
  - jupyter-lab
  - sphinx
  - sphinx-rtd-theme
  - sphinxcontrib-bibtex
  - sphinx-book-theme
  - sphinx-copybutton
  - sphinxcontrib-images
  - sphinxcontrib-seqdiag
  - sphinxcontrib-httpdomain